<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>modest-server-dev</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Modest.Core/Modest.Core.csproj" />
    <ProjectReference Include="../Modest.Codec/Modest.Codec.csproj" />
    <ProjectReference Include="../Modest.Issuance.InternalCa/Modest.Issuance.InternalCa.csproj" />
    <ProjectReference Include="../Modest.Issuance.HttpDelegate/Modest.Issuance.HttpDelegate.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Modest.Server.Tests" />
    <InternalsVisibleTo Include="Modest.Rfc7030.ComplianceTests" />
  </ItemGroup>

</Project>
