<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Modest.Core/Modest.Core.csproj" />
    <ProjectReference Include="../Modest.Codec/Modest.Codec.csproj" />
  </ItemGroup>

</Project>
